name: Jira Find issue key
description: Find an issue inside event
branding:
  icon: 'book-open'
  color: 'blue'
inputs:
  string:
    description: Provide a string to extract issue key from
    required: false
  from:
    description: Find from predefined place (should be either 'branch', or 'commits')
    required: false
    default: commits
  fields:
    description: csv of fields to return with queried issue
    required: false
outputs:
  key:
    description: Key of the found issue
  issue:
    description: Found issue in JIRA
runs:
  using: 'node12'
  main: './dist/index.js'
